# Generated by Django 3.2.23 on 2023-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('cc', models.BigIntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
    ]
