# Generated by Django 3.2.23 on 2023-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgym',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientgym',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
