# Generated by Django 3.2.23 on 2023-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_auto_20231205_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgym',
            name='cc',
            field=models.BigIntegerField(unique=True),
        ),
    ]
