# Generated by Django 5.2.4 on 2025-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_alter_clientgym_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgym',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientgym',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
