# Generated by Django 5.2.4 on 2025-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_clientgym_check_in_clientgym_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('birth_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
