# Generated by Django 5.2.4 on 2025-11-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='coachs'),
        ),
    ]
